"""Load payments from the configured datasource."""
import json
import logging
from pathlib import Path
from typing import List
from uuid import uuid4
from datetime import datetime

from app.models.payment import Payment, PaymentStatus

logger = logging.getLogger(__name__)

# Data directory: backend/data/
_DATA_DIR = Path(__file__).resolve().parent.parent.parent / "data"
_SAMPLE_FILE = _DATA_DIR / "sample_payments.json"
_STRIPE_SEED_FILE = _DATA_DIR / "stripe_payments.json"


def _load_json_payments(filepath: Path) -> List[Payment]:
    """Load payments from a JSON file. Returns empty list if file not found."""
    if not filepath.exists():
        logger.warning("Data file not found: %s", filepath)
        return []
    raw = json.loads(filepath.read_text())
    out = []
    for r in raw:
        created = datetime.fromisoformat(r["created_at"].replace("Z", "+00:00"))
        out.append(
            Payment(
                id=uuid4(),
                amount_cents=r["amount_cents"],
                currency=r.get("currency", "USD"),
                direction=r["direction"],
                counterparty=r.get("counterparty"),
                description=r.get("description"),
                status=PaymentStatus(r.get("status", "completed")),
                created_at=created,
                updated_at=None,
                external_id=r.get("external_id"),
            )
        )
    out.sort(key=lambda p: p.created_at, reverse=True)
    return out


def load_payments_from_datasource() -> List[Payment]:
    """Load payments based on the DATASOURCE setting.

    - "sample":      backend/data/sample_payments.json (default)
    - "stripe":      live from stripe-mock via HTTP
    - "stripe_seed": backend/data/stripe_payments.json (generated by seed script)
    """
    from app.config import settings

    ds = settings.datasource.lower()

    if ds == "stripe":
        from app.services.stripe_datasource import load_payments_from_stripe_mock
        payments = load_payments_from_stripe_mock()
        if payments:
            logger.info("Loaded %d payments from stripe-mock", len(payments))
            return payments
        logger.warning("stripe-mock returned no data, falling back to sample")
        return _load_json_payments(_SAMPLE_FILE)

    if ds == "stripe_seed":
        payments = _load_json_payments(_STRIPE_SEED_FILE)
        if payments:
            logger.info("Loaded %d payments from stripe seed file", len(payments))
            return payments
        logger.warning("Stripe seed file not found, falling back to sample")
        return _load_json_payments(_SAMPLE_FILE)

    # Default: sample
    return _load_json_payments(_SAMPLE_FILE)
